---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    get:
      summary: Retrieves Cars
      tags:
      - Cars
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: per_page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Cars retrieved
    post:
      summary: Create a Car
      tags:
      - Cars
      parameters: []
      responses:
        '201':
          description: Car created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                brand:
                  type: string
                model:
                  type: string
                finance_fee:
                  type: integer
                purchase_fee:
                  type: integer
                tap:
                  type: integer
                duration:
                  type: integer
                description:
                  type: text
                image:
                  type: blob
              required:
              - brand
              - finance_fee
              - model
              - image
              - tap
              - duration
              - description
          application/xml:
            schema:
              type: object
              properties:
                brand:
                  type: string
                model:
                  type: string
                finance_fee:
                  type: integer
                purchase_fee:
                  type: integer
                tap:
                  type: integer
                duration:
                  type: integer
                description:
                  type: text
                image:
                  type: blob
              required:
              - brand
              - finance_fee
              - model
              - image
              - tap
              - duration
              - description
  "/api/v1/cars/:id":
    delete:
      summary: Delete Car
      tags:
      - Car
      parameters: []
      responses:
        '201':
          description: Car deleted
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
          application/xml:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
  "/api/v1/reservations":
    get:
      summary: Retrieves Reservations
      tags:
      - Reservations
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: per_page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Reservations retrieved
  "/api/v1/:user_username/reservations":
    post:
      summary: Create a Reservation
      tags:
      - Reservations
      parameters: []
      responses:
        '201':
          description: Reservation created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: date
                city:
                  type: string
                car_id:
                  type: bigint
                user_id:
                  type: bigint
              required:
              - date
              - city
              - car_id
              - user_id
          application/xml:
            schema:
              type: object
              properties:
                date:
                  type: date
                city:
                  type: string
                car_id:
                  type: bigint
                user_id:
                  type: bigint
              required:
              - date
              - city
              - car_id
              - user_id
  "/api/v1/:user_username/reservations/:id":
    delete:
      summary: Delete Reservation
      tags:
      - Reservation
      parameters: []
      responses:
        '201':
          description: Reservation deleted
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
          application/xml:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
