---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    get:
      summary: Retrieves Cars
      tags:
      - Cars
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: per_page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Cars retrieved
  "/api/v1/sessions":
    post:
      summary: Create a user session
      tags:
      - User session
      parameters: []
      responses:
        '404':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
          application/xml:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
  "/api/v1/users":
    post:
      summary: Create a User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: User created
        '400':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
          application/xml:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
